name: "AWS Proxy pipeline"

on:
 push:
   branches:
   - main
   paths:
   - src/aws-db-proxy/**

jobs:
  aws-db-proxy:
    runs-on: ubuntu-latest
    name: Temporary output job

    steps:
      - name: Hygiene check
        run: echo "AWS Proxy pipeline"