name: "Infrastructure as Code pipeline"

on:
 push:
   branches:
   - main
   paths:
   - tf/**

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    name: Temporary output job

    steps:
      - name: Hygiene check
        run: echo "IaC pipeline"