name: "Main App Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - src/main-app/**

jobs:
  build-and-push-main-app:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      registry: ${{ vars.REGISTRY_TO_PUSH_TO }}
      image-name: ${{ github.actor }}/${{ vars.MAIN_APP_IMAGE }}
      working-directory: ./src/main-app
    secrets: inherit

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  deploy-azure:
    runs-on: ubuntu-latest

    needs: build-and-push-main-app

    steps:
      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.RESOURCE_GROUP_NAME }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      - name: Apply latest Azure Manifest
        id: deploy-aks
        run: |
          kubectl set image deployment/main-app \
            main-app=${{ vars.REGISTRY_TO_PUSH_TO }}/ivesey/${{ vars.MAIN_APP_IMAGE}}:sha-${{ github.sha }} \
            --namespace gha-demo-azure

  deploy-aws:
    runs-on: ubuntu-latest

    needs: build-and-push-main-app

    defaults:
      run:
        shell: bash

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-demo
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Set EKS context
        id: set-eks-context
        run: |
          aws eks update-kubeconfig \
            --name ${{ vars.EKS_CLUSTER_NAME }} \
            --region ${{ vars.AWS_REGION }}

      - name: Apply latest AWS Manifest
        id: deploy-eks
        run: |
          kubectl set image deployment/main-app \
            main=${{ vars.REGISTRY_TO_PUSH_TO }}/ivesey/${{ vars.MAIN_APP_IMAGE}}:sha-${{ github.sha }} \
            --namespace gha-demo-aws
