name: "Main App Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - src/main-app/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/gha-demo-main-app
  WORKING_DIRECTORY: ./src/main-app

jobs:
  build-and-push-main-app:
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      registry: ghcr.io
      image-name: ${{ github.actor }}/gha-demo-main-app
      working-directory: ./src/main-app
    secrets: inherit

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write