name: "Teardown pipeline"

on:
  workflow_dispatch:

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    name: Teardown EKS and AKS clusters
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./tf

    steps:
      - name: Checkout the repository to the runner
        id: checkout
        uses: actions/checkout@v2
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-demo
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # these three steps are necessary because TF doesn't know abut the LB resource
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Set EKS context
        id: set-eks-context
        run: |
          aws eks update-kubeconfig \
            --name ${{ vars.EKS_CLUSTER_NAME }} \
            --region ${{ vars.AWS_REGION }}
      - name: Manually delete gha-demo-aws namespace and the LB and the Security Group
        run: |
          kubectl delete namespace gha-demo-aws
        continue-on-error: true
        # if the namespace doesn't exist it's really not a problem.
      ###############################################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
    
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_TF_STATE }}"
 
      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -input=false \
            -var eks_cluster_name=${{ vars.EKS_CLUSTER_NAME }} \
            -var aws_region=${{ vars.AWS_REGION }} \
            -var aks_cluster_name=${{ vars.AKS_CLUSTER_NAME }} \
            -var resource_group_name=${{ vars.RESOURCE_GROUP_NAME }} \
            -var resource_group_location=${{ vars.RESOURCE_GROUP_LOCATION }}
